Responsavel.WebMVC/Controllers/AmbienteAvaliacaoSimuladoController.cs
using System.Diagnostics;
using System.Reflection;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using Responsavel.WebMVC.App_Helpers;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class AmbienteAvaliacaoSimuladoController : BaseController
    {
        private readonly IUsuarioAppService _usuario;

        public AmbienteAvaliacaoSimuladoController(IUsuarioAppService usuario)
        {
            _usuario = usuario;
        }

        // GET: AmbienteAvaliacao
        public ActionResult Index()
        {
            ApplicationCookies.DefinirCookieUsuario(ControllerContext, _usuario, UserId);

            var assembly = Assembly.GetExecutingAssembly();
            var fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
            var version = fvi.FileVersion;
            ViewBag.AtenaVersion = $"{version}";

            return View();
        }
    }
}

Responsavel.WebMVC/Controllers/AmbienteMinhasAtividadesController.cs
using System.Diagnostics;
using System.Reflection;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using Responsavel.WebMVC.App_Helpers;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class AmbienteMinhasAtividadesController : BaseController
    {
        // GET: AmbienteMinhasAtividades
        private readonly IUsuarioAppService _usuario;

        public AmbienteMinhasAtividadesController(IUsuarioAppService usuario)
        {
            _usuario = usuario;
        }

        public ActionResult Index()
        {
            ApplicationCookies.DefinirCookieUsuario(ControllerContext, _usuario, UserId);

            var assembly = Assembly.GetExecutingAssembly();
            var fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
            var version = fvi.FileVersion;
            ViewBag.AtenaVersion = $"{version}";

            return View();
        }
    }
}

Responsavel.WebMVC/Controllers/AmbienteNotasDisciplinaresController.cs
using System.Diagnostics;
using System.Reflection;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using Responsavel.WebMVC.App_Helpers;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class AmbienteNotasDisciplinaresController : BaseController
    {
        // GET: AmbienteNotasDisciplinares
        private readonly IUsuarioAppService _usuario;

        public AmbienteNotasDisciplinaresController(IUsuarioAppService usuario)
        {
            _usuario = usuario;
        }

        public ActionResult Index()
        {
            ApplicationCookies.DefinirCookieUsuario(ControllerContext, _usuario, UserId);

            var assembly = Assembly.GetExecutingAssembly();
            var fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
            var version = fvi.FileVersion;
            ViewBag.AtenaVersion = $"{version}";

            return View();
        }

    }
}

Responsavel.WebMVC/Controllers/AmbienteRedacaoController.cs
using System.Diagnostics;
using System.Reflection;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using Responsavel.WebMVC.App_Helpers;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class AmbienteRedacaoController : BaseController
    {
        // GET: AmbienteRedacao
        private readonly IUsuarioAppService _usuario;

        public AmbienteRedacaoController(IUsuarioAppService usuario)
        {
            _usuario = usuario;
        }

        public ActionResult Index()
        {
            ApplicationCookies.DefinirCookieUsuario(ControllerContext, _usuario, UserId);

            var assembly = Assembly.GetExecutingAssembly();
            var fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
            var version = fvi.FileVersion;
            ViewBag.AtenaVersion = $"{version}";

            return View();
        }

    }
}

Responsavel.WebMVC/Controllers/HomeController.cs
using System.Diagnostics;
using System.Reflection;
using System.Web.Mvc;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            var assembly = Assembly.GetExecutingAssembly();
            var fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
            var version = fvi.FileVersion;
            ViewBag.AgendaDoEstudanteVersion = $"{version}";
            return View();
        }

    }
}

Responsavel.WebMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<section class="content">

    <div class="container-fluid">
        
        <div class="row">
            @{
                Html.RenderPartial("_layoutEscola");
            }

        </div>

        <div class="row">

            <div class="col-lg-8 col-md-8 col-sm-8 ml-auto mr-auto">

                <div class="row">
                    <div class="col-md-12 text-center">
                        <h2 class="title">Área do Responsável</h2>
                        <h5 class="description">Selecione abaixo um dos ambientes da área do responsável para ter acesso aos menus.</h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-pricing">
                            <h6 class="card-category">Minhas Atividades</h6>
                            <div class="card-body">
                                <div class="card-icon">
                                    <i class="material-icons">event_note</i>
                                </div>
                                <h3 class="card-title">Minhas Atividades</h3>
                                <p class="card-description">Dados das minhas atividades</p>
                            </div>
                            <div class="card-footer-botao">
                                @Html.ActionLink("Acessar ambiente...", "Index", "AmbienteMinhasAtividades", new {area = ""}, new {@class = "btn btn-round", data_background_color = "blue"})
                            </div>

                        </div>
                    </div>


                    <div class="col-md-6">
                        <div class="card card-pricing ">
                            <h6 class="card-category">Avaliação e Simulados</h6>
                            <div class="card-body">
                                <div class="card-icon">
                                    <i class="material-icons">dashboard</i>
                                </div>
                                <h3 class="card-title">Avaliação e Simulados</h3>
                                <p class="card-description">Relatório de simulados e avaliações</p>
                            </div>
                            <div class="card-footer-botao">
                                @Html.ActionLink("Acessar ambiente...", "Index", "AmbienteAvaliacaoSimulado", new {area = ""}, new {@class = "btn btn-round", data_background_color = "blue"})
                            </div>
                        </div>
                    </div>

                    @if (User.IsInRole("01-LINTE-ADMINISTRACAO"))
                    {
                        <div class="col-md-6">
                            <div class="card card-pricing">
                                <h6 class="card-category">Redação</h6>
                                <div class="card-body">
                                    <div class="card-icon">
                                        <i class="material-icons">description</i>
                                    </div>
                                    <h3 class="card-title">Redação</h3>
                                    <p class="card-description">Configuração de redações</p>
                                </div>
                                <div class="card-footer-botao">
                                    @Html.ActionLink("Acessar ambiente...", "Index", "AmbienteRedacao", new {area = ""}, new {@class = "btn btn-round", data_background_color = "blue"})
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card card-pricing">
                                <h6 class="card-category">Notas Disciplinares</h6>
                                <div class="card-body">
                                    <div class="card-icon">
                                        <i class="material-icons">spellcheck</i>
                                    </div>
                                    <h3 class="card-title">Notas Disciplinares</h3>
                                    <p class="card-description">Dados das notas disciplinares</p>
                                </div>
                                <div class="card-footer-botao">
                                    @Html.ActionLink("Acessar ambiente...", "Index", "AmbienteNotasDisciplinares", new {area = ""}, new {@class = "btn btn-round", data_background_color = "blue"})
                                </div>
                            </div>
                        </div>
                    }

                </div>

            </div>
        </div>

    </div>

</section>

Responsavel.WebMVC/Views/Home/_halloween.cshtml
<div class="bodyGhost">
    <div class="candyTrail">
        <div class="candycorn"></div>
        <div class="candy"></div>
        <div class="candy"></div>
        <div class="candycorn"></div>
        <div class="candy"></div>
        <div class="candycorn"></div>
        <div class="candycorn"></div>
        <div class="candy"></div>
        <div class="candycorn"></div>
    </div>
    <div class="ghost">
        <div class="tail"></div>
        <div class="eyes">
            <div class="eye"></div>
            <div class="eye"></div>
        </div>
        <div class="mouth"></div>
        <div class="bucket">
            <div class="candy"></div>
        </div>
        <div class="hand"></div>
    </div>
    <div class="shadow"></div>
</div>

Responsavel.WebMVC/Views/Home/_halloween2.cshtml
<div class="ghost-container">
    <div class="ghost">
        <div class="body-top">
            <div class="eyes">
                <div class="eye eye-left"></div>
                <div class="eye eye-right"></div>
            </div>
        </div>
        <div class="body-low">
        </div>
        <div class="hand"></div>
        <div class="skirt"></div>
    </div>
    <div class="shadow"></div>
</div>

<!-- <div id="title">strange industries</div> -->

Responsavel.WebMVC/Views/Home/_menuAdministradorLateral.cshtml
<script type="text/javascript">

    var JSONMenuLateral = {
        menu:
            [
                {
                    descricao: 'Dados Escolares', icone: 'school', ref: 'menuLateralDadosEscolares', classContent: 'active show', sub:
                    [
                        {
                            descricao: 'Escola', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Escola', actionName: ''
                        },
                        {
                            descricao: 'Professor', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Professor', actionName: ''
                        },
                        {
                            descricao: 'Turma', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Turma', actionName: ''
                        },
                        {
                            descricao: 'Ano Escolar', icone: '', ref: '', classContent: '', sub: null, controllerName: 'AnoEscolar', actionName: ''
                        },
                        {
                            descricao: 'Segmento', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Segmento', actionName: ''
                        }

                    ]
                },
                {
                    descricao: 'Dados Personalizados', icone: 'build', ref: 'menuLateralDadosPersonalizados', classContent: '', sub:
                    [
                        {
                            descricao: 'Áreas', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Area', actionName: ''
                        },
                        {
                            descricao: 'Disciplina', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Disciplina', actionName: ''
                        }

                    ]
                },
                {
                    descricao: 'Planejamento', icone: 'dashboard', ref: 'menuLateralPlanejamento', classContent: '', sub:
                    [
                        {
                            descricao: 'Tarefas', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Tarefa', actionName: ''
                        },
                        {
                            descricao: 'Aulas', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Aula', actionName: ''
                        },
                        {
                            descricao: 'Trabalhos', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Trabalho', actionName: ''
                            },
                        {
                            descricao: 'Exames', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Exame', actionName: ''
                        }

                    ]
                },
                {
                    descricao: 'Minhas Atividades', icone: 'event_note', ref: 'menuLateralMinhasAtividades', classContent: '', sub:
                    [
                        {
                            descricao: 'Resumo', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Resumo', actionName: ''
                        },
                        {
                            descricao: 'Timeline', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Timeline', actionName: ''
                        },
                        {
                            descricao: 'Calendário do Ano', icone: '', ref: '', classContent: '', sub: null, controllerName: 'Calendario', actionName: ''
                        },
                        {
                            descricao: 'Horário-Programado', icone: '', ref: '', classContent: '', sub: null, controllerName: 'HorarioProgramado', actionName: ''
                        }
                    ]
                },
                {
                    descricao: 'Ajuda', icone: 'help_outline', ref: 'menuLateralAjuda', classContent: '', sub:
                    [
                        {
                            descricao: 'Ajuda', icone: '', ref: 'menuAjuda', classContent: 'active', sub:
                            [
                                 { descricao: 'Fale conosco', detalhe: 'Obter suporte', icone: 'looks_two', controllerName: 'Suporte', actionName: 'Index' }
                            ]
                        }
                    ]
                }
            ]
    }

</script>

Responsavel.WebMVC/Views/Home/_menuEstudanteLateral.cshtml
<script type="text/javascript">

    var JSONMenuLateral = {
        menu:
            [
                
                {
                    descricao: 'Relatórios', icone: 'trending_up', ref: 'menuLateralRelatoriosRedacao', classContent: 'active', sub:
                        [
                            {
                                descricao: 'Quantitativo', icone: '', ref: 'menuLateralRelatorioRedacaoQuantitativo', classContent: 'active', sub:
                                    [
                                        { descricao: 'Área', detalhe: 'Relatório quantitativo por área.', icone: 'looks_one', controllerName: 'RelatorioquantitativoArea', actionName: 'Index' },
                                        { descricao: 'Disciplina', detalhe: 'Relatório quantitativo por disciplina.', icone: 'looks_two', controllerName: 'RelatorioquantitativoDisciplina', actionName: 'Index' },
                                        { descricao: 'Distribuição das Respostas', detalhe: 'Aqui você verá a quantidade de vezes que cada alternativa foi marcada em cada questão.', icone: 'looks_4', controllerName: 'RelatorioquantitativoDistribuicao', actionName: 'Index' }
                                    ]
                            },
                            {
                                descricao: 'Qualitativo', icone: '', ref: 'menuLateralRelatorioRedacaoQualitativo', classContent: '', sub:
                                    [
                                        { descricao: 'Análise dos Descritores de Aprendizagem', detalhe: 'Aqui há os dados referentes aos descritores de aprendizagem desenvolvidos na avaliação analisada.', icone: 'looks_one', controllerName: 'RelatorioQualitativoDescritor', actionName: 'Index' }
                                    ]
                            }
                        ]
                },
                {
                    descricao: 'Ajuda', icone: 'help_outline', ref: 'menuLateralAjuda', classContent: '', sub:
                    [
                        {
                            descricao: 'Ajuda', icone: '', ref: 'menuAjuda', classContent: 'active', sub:
                            [
                                 { descricao: 'Fale conosco', detalhe: 'Obter suporte', icone: 'looks_two', controllerName: 'Suporte', actionName: 'Index' }
                            ]
                        }
                    ]
                }
            ]
    }

</script>

Responsavel.WebMVC/Views/Home/_menuParticipante.cshtml
<script type="text/javascript">

    var JSON = {
        menu:
        [
            {
                descricao: 'Meus eventos', icone: 'supervisor_account', ref: 'menuSuperiorEventos', classContent: 'active show', sub:
                [
                    {
                        descricao: 'Opções', icone: '', ref: 'menuOpcoesEvento', classContent: 'active show', sub:
                        [
                                { descricao: 'Emissão de certificado', detalhe: '<span>Utilize essa opção para imprimir os certificados disponíveis para os eventos que você participou.</span><br/><span>Alguns eventos <span style="font-weight:bold">exigem participação e controle de frequência</span>, caso você não encontre seu certificado, verifique na opção abaixo as frequencias que você possui.</span><p></p><p>Recomendamos o uso do navegador <span style="font-weight:bold;color:maroon">Google Chrome</span> para impressão do certificado, em alguns navagadores o modelo poderá quebrar em duas paginas.</p>', icone: 'looks_one', controllerName: 'CertificadoParticipante', actionName: 'Index' },
                            { descricao: 'Dados de frequência', detalhe: 'Utilize essa opção para exibir o relatório de frequências coletados nos eventos que você participou.', icone: 'looks_one', controllerName: 'FrequenciaParticipante', actionName: 'Index' },

                        ]
                    }
                ]
            },
            {
                descricao: 'Ajuda', icone: 'help_outline', ref: 'menuSuperiorAjuda', classContent: '', sub:
                [
                    {
                        descricao: 'Ajuda', icone: '', ref: 'menuAjuda', classContent: 'active', sub:
                        [
                            { descricao: 'Fale conosco', detalhe: 'Obter suporte', icone: 'looks_two', controllerName: 'Suporte', actionName: 'Index' },
                            { descricao: '@ViewBag.AgendaDoEstudanteVersion', detalhe: 'Versão do software Agenda do Estudante', icone: 'looks_3', controllerName: '', actionName: '' }
                        ]
                    }
                ]
            }
        ]
    }

</script>