Responsavel.WebMVC/Models/Shared/BarraDashboardViewModel.cs
// 21:28 03 04 2018  AvaliacaoDiagnostica.WebMVC  AvaliacaoDiagnostica.Solution

using System.Collections.Generic;

namespace Responsavel.WebMVC.Models.Shared
{
    public class BarraDashboardViewModel
    {
        public List<ItemBarraDashboardViewModel> Item { get; set; }
    }

    public class ItemBarraDashboardViewModel
    {
        public string Icone { get; set; }
        public decimal Valor { get; set; }
        public string Descricao { get; set; }
        public string CssCorBarra { get; set; }
        public string Mensagem { get; set; }
    }
}

Responsavel.WebMVC/Models/Shared/CertificadoModel.cs
namespace Responsavel.WebMVC.Models.Shared
{
    public class CertificadoModel
    {
        public string NomeCertificado { get; set; }
        public string ImagemParte1 { get; set; }
        public string ImagemParte2 { get; set; }
    }
}

Responsavel.WebMVC/Models/Shared/DataResultMessageModel.cs
namespace Responsavel.WebMVC.Models.Shared
{
    public class DataResultMessageModel
    {
        public string mensagem { get; set; }
        public bool status { get; set; }
    }
}

Responsavel.WebMVC/Models/Shared/ModelPaginacaoEOrdenacao.cs
namespace Responsavel.WebMVC.Models.Shared
{
    public class ModelPaginacaoEOrdenacao
    {
        public int? Page { get; set; }
        public string SortOrder { get; set; }
        public string SortOld { get; set; }
        public string SortDirection { get; set; }
        public int TotalRegistros { get; set; }

        public string UrlRetorno { get; set; }
        public string PesquisaUrlRetorno { get; set; }
        public string PaginacaoEOrdenacaoUrlRetorno { get; set; }

    }
}

Responsavel.WebMVC/Models/Shared/ModelPesquisaEOrdenacao.cs
namespace Responsavel.WebMVC.Models.Shared
{
    public class ModelPesquisaEOrdenacao
    {
        public int? Page { get; set; }
        public string SortOrder { get; set; }
        public string SortOld { get; set; }
        public string SortDirection { get; set; }
        public int TotalRegistros { get; set; }

        public bool NaoExibirTotalRegistros { get; set; }

        // resultados de Insert/Update
        public bool ActionResult { get; set; }
        public string ActionMessage { get; set; }
        public int ActionRegistroId { get; set; }
    }
}

Responsavel.WebMVC/Models/Shared/PerfilUsuarioViewModel.cs
namespace Responsavel.WebMVC.Models.Shared
{
    public class PerfilUsuarioViewModel
    {
        public string Nome { get; set; }
        public string ImagemPerfil { get; set; }
    }
}

Responsavel.WebMVC/Controllers/AmbienteAvaliacaoSimuladoController.cs
using System.Diagnostics;
using System.Reflection;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using Responsavel.WebMVC.App_Helpers;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class AmbienteAvaliacaoSimuladoController : BaseController
    {
        private readonly IUsuarioAppService _usuario;

        public AmbienteAvaliacaoSimuladoController(IUsuarioAppService usuario)
        {
            _usuario = usuario;
        }

        // GET: AmbienteAvaliacao
        public ActionResult Index()
        {
            ApplicationCookies.DefinirCookieUsuario(ControllerContext, _usuario, UserId);

            var assembly = Assembly.GetExecutingAssembly();
            var fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
            var version = fvi.FileVersion;
            ViewBag.AtenaVersion = $"{version}";

            return View();
        }
    }
}

Responsavel.WebMVC/Controllers/AmbienteMinhasAtividadesController.cs
using System.Diagnostics;
using System.Reflection;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using Responsavel.WebMVC.App_Helpers;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class AmbienteMinhasAtividadesController : BaseController
    {
        // GET: AmbienteMinhasAtividades
        private readonly IUsuarioAppService _usuario;

        public AmbienteMinhasAtividadesController(IUsuarioAppService usuario)
        {
            _usuario = usuario;
        }

        public ActionResult Index()
        {
            ApplicationCookies.DefinirCookieUsuario(ControllerContext, _usuario, UserId);

            var assembly = Assembly.GetExecutingAssembly();
            var fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
            var version = fvi.FileVersion;
            ViewBag.AtenaVersion = $"{version}";

            return View();
        }
    }
}

Responsavel.WebMVC/Controllers/AmbienteRedacaoController.cs
using System.Diagnostics;
using System.Reflection;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using Responsavel.WebMVC.App_Helpers;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class AmbienteRedacaoController : BaseController
    {
        // GET: AmbienteRedacao
        private readonly IUsuarioAppService _usuario;

        public AmbienteRedacaoController(IUsuarioAppService usuario)
        {
            _usuario = usuario;
        }

        public ActionResult Index()
        {
            ApplicationCookies.DefinirCookieUsuario(ControllerContext, _usuario, UserId);

            var assembly = Assembly.GetExecutingAssembly();
            var fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
            var version = fvi.FileVersion;
            ViewBag.AtenaVersion = $"{version}";

            return View();
        }

    }
}

Responsavel.WebMVC/Controllers/MeuPerfilController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using AMais.Responsavel.DTO;
using Linte.Core.DomainEvent.Events;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage.RetryPolicies;
using Responsavel.WebMVC.App_Helpers;
using Responsavel.WebMVC.Models.MeuPerfil;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class MeuPerfilController : BaseController
    {
        private readonly IUsuarioAppService _usuarioAppService;
        private readonly IPerfilResponsavelAppService _responsavelAppService;

        private async Task<ViewModelParaMeuPerfil> CarregarViewData(ViewModelParaMeuPerfil model = null)
        {
            if (model == null) model = new ViewModelParaMeuPerfil() { RegistroUsuario = new PerfilResponsavelDTO() };

            var task = Task.Run(() => _responsavelAppService.ObterDadosDoUsuario(UserId));
            model.RegistroUsuario = await task;

            return model;
        }

        public MeuPerfilController(IUsuarioAppService usuarioAppService, IPerfilResponsavelAppService responsavelAppService)
        {
            _usuarioAppService = usuarioAppService;
            _responsavelAppService = responsavelAppService;
        }

        public async Task<ActionResult> Index()
        {
            GetModelStateData();

            ViewModelParaMeuPerfil model;

            if (TempData["Model"] == null)
            {
                model = await CarregarViewData();
                return View(model);
            }
            
            model = (ViewModelParaMeuPerfil)TempData["Model"];
            TempData["Model"] = null;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> SalvarDadosAsync(ViewModelParaMeuPerfil model, HttpPostedFileBase files)
        {
            if (files != null && files.ContentLength > 0)
            {
                ApagarImagemPerfil();
                var fileName = $"{UserId}-{new Random().Next()}{Path.GetExtension(files.FileName)}";
                await SalvarImagemPerfil(files, fileName);
                model.RegistroUsuario.CaminhoImagem = $"https://lintelligencehd.blob.core.windows.net/responsavel-imagem-perfil/{fileName}";
            }

            if (!ModelState.IsValid) return View("Index", await CarregarViewData(model));

            var guid = Guid.Parse(UserId);

            model.RegistroUsuario.UsuarioId = guid;

            var dataResult = _responsavelAppService.AdicionarOuAtualizar(model.RegistroUsuario);
            ValidarErrosDominio(dataResult.Message);

            if (!dataResult.Result) return View("Index", await CarregarViewData(model));

            TempData["Model"] = model;
            ApplicationCookies.LimparCookieUsuario(ControllerContext);
            ApplicationCookies.DefinirCookieUsuarioWithForceReload(ControllerContext, _usuarioAppService, UserId);
            return await Task.Run<ActionResult>(() => RedirectToAction("Index"));
        }
        
        private void ApagarImagemPerfil()
        {
            LinteAzureStorage.ApagarArquivo(UserId, Notifications);
        }

        private async Task<bool> SalvarImagemPerfil(HttpPostedFileBase files, string fileName)
        {
            if (files.ContentLength > 1536000)
            {
                Notifications.Handle(new DomainNotification("ImgUpLoadError", "A imagem selecionada não é válida para upload, selecione uma imagem menor!"));
                ModelState.AddModelError("Erro ao salvar imagem do usuário", "Tamanho do arquivo não permitido");
                return false;
            }
            else
            {
                var storageAccount = LinteAzureStorage.CreateStorageAccountFromConnectionString();
                var blobClient = storageAccount.CreateCloudBlobClient();
                var container = blobClient.GetContainerReference("responsavel-imagem-perfil");
                try
                {
                    var requestOptions = new BlobRequestOptions() { RetryPolicy = new NoRetry() };
                    await container.CreateIfNotExistsAsync(requestOptions, null);
                }
                catch (StorageException e)
                {
                    Notifications.Handle(new DomainNotification("ErroStorage", e.Message));
                    ModelState.AddModelError("Erro ao salvar imagem do usuário", e);
                    throw;
                }
                var blockBlob = container.GetBlockBlobReference(fileName);
                blockBlob.Properties.ContentType = files.ContentType;
                using (var fileStream = files.InputStream)
                {
                    await blockBlob.UploadFromStreamAsync(fileStream);
                }
                return true;
            }
        }
    }
}

Responsavel.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>@ViewBag.Title - Área do Responsável</title>

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- CSS Files -->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")

    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'1b8aa4d8-5993-47ef-ba10-bbaedc2f559f'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>

<body id="form-principal" class="sidebar-mini">

    <div class="wrapper ">

        @{
            Html.RenderPartial("_MenuLateral");
        }

        <main class="main-panel">

            @{
                Html.RenderPartial("_MenuSuperior");
                Html.RenderPartial("_MensagensNotificacoes");
            }
            @RenderBody()
            @{Html.RenderPartial("_footer");}
        </main>
    </div>

    

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/material-design")
    @Scripts.Render("~/bundles/linte-scripts")

    @RenderSection("scripts", required: false)

</body>

</html>

Responsavel.WebMVC/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>@ViewBag.Title - A+ Área do Responsável</title>

    <!--     Fontes e icones     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")

</head>

<body class="off-canvas-sidebar">

    @{
        Html.RenderPartial("_MenuSuperiorLogin");
        Html.RenderPartial("_MensagensNotificacoes");

    }

    <div class="wrapper wrapper-full-page">

            @RenderBody()

        </div>

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/linte-scripts")
    @Scripts.Render("~/bundles/material-design")

    @RenderSection("scripts", required: false)
</body>
</html>

Responsavel.WebMVC/Views/Shared/_LayoutErrorPadrao.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>@ViewBag.Title - Responsável Inscrição</title>

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- CSS Files -->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
</head>

<body id="form-principal" class="sidebar-mini">

<div class="wrapper ">

    @{
        Html.RenderPartial("_MenuLateral");
    }

    <main class="main-panel">

        @{
            Html.RenderPartial("_MenuSuperior");
            Html.RenderPartial("_MensagensNotificacoes");
        }
        @RenderBody()
        @{Html.RenderPartial("_footer");}
    </main>
</div>

    
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/linte-scripts")
@Scripts.Render("~/bundles/material-design")

@RenderSection("scripts", required: false)

</body>

</html>

Responsavel.WebMVC/Views/Shared/_MensagensNotificacoes.cshtml
<section class="registros-alertas">

    @if (ViewData.ModelState.IsValid && !string.IsNullOrEmpty(ViewBag.StatusMessage))
    {
        <input type="hidden" data-value="@ViewBag.StatusMessage" id="mensagemSucesso" />

        <script type="text/javascript" language="JavaScript">

            $(document).ready(function () {

                var mensagem = $("#mensagemSucesso").data("value");
                //var mensagem = document.getElementById('mensagemSucesso');
                //mensagemAlerta('sucesso-na-validacao', mensagem.value);
                //type = ['', 'info', 'success', 'warning', 'danger', 'rose', 'primary'];

                $.notify({
                    icon: "notifications",
                    message: "<b> Responsavel </b> - " + mensagem

                }, {
                    type: 'success',
                    timer: 3000,
                    placement: {
                        from: 'top',
                        align: 'center'
                    }
                });

            });
        </script>

    }

    @if (!ViewData.ModelState.IsValid)
    {

        if (string.IsNullOrEmpty(ViewBag.ErrosDominio))
        {
            ViewBag.ErrosDominio = "";
            foreach (var listError in ViewData.ModelState)
            {
                foreach (var error in listError.Value.Errors)
                {
                    ViewBag.ErrosDominio += error.ErrorMessage;
                }
                
             }

        }
        <input type="hidden" value="@ViewBag.ErrosDominio" id="errorDomain" />

        <script type="text/javascript" language="JavaScript">

            var erro = document.getElementById('errorDomain');

            $(document).ready(function () {
                mensagemAlerta('erro-na-validacao', erro.value);
            });


        </script>

    }

</section>

Responsavel.WebMVC/Views/Shared/_MenuLateral.cshtml
<div id="modalElements">

</div>

<div class="sidebar" data-color="black" data-background-color="black">

    <div class="logo">
        @Html.ActionLink("AR", "Index", "Home", new { area = "" }, new { @class = "simple-text logo-mini" })
        @Html.ActionLink("Área do Responsável", "Index", "Home", new { area = "" }, new { @class = "simple-text logo-normal" })

    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="photo">
                @if (!string.IsNullOrEmpty(TempData["imageName"]?.ToString()))
                {
                    <img src=@TempData["imageName"] />
                }
                else
                {
                    <img src="~/Content/imagens/NO-IMAGE.png" />
                }
            </div>
            <div class="user-info">
                <a data-toggle="collapse" href="#collapsePerfil" class="username">
                    @if (TempData["userName"] != null && TempData["userName"].ToString().Length > 1)
                    {
                        <span>
                            @TempData["userName"]
                            <b class="caret"></b>
                        </span>
                    }
                    else
                    {
                        <span>
                            Preencha o seu Perfil
                            <b class="caret"></b>
                        </span>
                    }
                </a>

                <div class="clearfix"></div>

                <div class="collapse" id="collapsePerfil">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "MeuPerfil")">
                                <span class="sidebar-mini">MP</span>
                                <span class="sidebar-normal">Meu Perfil</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Manage")">
                                <span class="sidebar-mini">GC</span>
                                <span class="sidebar-normal">Gerenciar Conta</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <ul id="navBarLateral"></ul>

    </div>
</div>


@if (User.IsInRole("01-LINTE-ADMINISTRACAO"))
{
    Html.RenderPartial("~/views/home/_menuAdministradorLateral.cshtml");
}
else
{
    Html.RenderPartial("~/views/home/_menuEstudanteLateral.cshtml");
}

Responsavel.WebMVC/Views/Shared/_MenuSuperior.cshtml
<header>

    <nav class="navbar navbar-expand-lg navbar-absolute fixed-top" id="navigation-example">
        <div class="container-fluid">
            <div class="navbar-wrapper">
                <span class="navbar-brand"> @ViewBag.Title </span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation" data-target="#navigation-example">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
                <span class="navbar-toggler-icon icon-bar"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Index", "Home", new {area =""}) title="Home">
                            <i class="material-icons">home</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Index", "AmbienteMinhasAtividades", new {area =""}) title="Minhas Atividades">
                            <i class="material-icons">event_note</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=@Url.Action("Index", "AmbienteAvaliacaoSimulado", new {area =""}) title="Avaliação e Simulados">
                            <i class="material-icons">dashboard</i>
                        </a>
                    </li>
                    @if (User.IsInRole("01-LINTE-ADMINISTRACAO"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" href=@Url.Action("Index", "AmbienteRedacao", new {area =""}) title="Redação">
                                <i class="material-icons">description</i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href=@Url.Action("Index", "AmbienteNotasDisciplinares", new {area =""}) title="Notas Disciplinares">
                                <i class="material-icons">spellcheck</i>
                            </a>
                        </li>

                    }
                    <li class="hr-botao"></li>


                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#linte" id="navbarLogin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">person</i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarLogin">
                            <a href=@Url.Action("Index", "MeuPerfil") class="dropdown-item">Alterar meus dados de perfil</a>
                            <a href=@Url.Action("ChangePassword", "Manage") class="dropdown-item">Alterar minha senha</a>
                            <hr/>
                            <a href=@Url.Action("LogOff", "Account") class="dropdown-item">Sair do ambiente - @HttpContext.Current.User.Identity.Name</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

@*<script type="text/javascript">

    $(document).ready(function () {

        $("#btnIrPara").click(function(e){
            var url = document.getElementById(document.getElementById("getIrPara").value.toUpperCase()).href;
            e.preventDefault();
            window.location = url;
        });


        $("#minimizeSidebar").click(function (e) {

            if ($.cookie("sidebar-mini") === '1')
                $.cookie("sidebar-mini", "0", { expires: 30 });
            else
                $.cookie("sidebar-mini", "1", { expires: 30 });
        });


    });


</script>*@

Responsavel.WebMVC/Views/Shared/_MenuSuperiorLogin.cshtml
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top text-white" id="navigation-example">
    <div class="container">
        <div class="navbar-wrapper">
            <a class="navbar-brand" href="#linte">A+ Área do Responsável - @ViewBag.Title</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation" data-target="#navigation-example">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="@Url.Action("Register", "Account")">
                        <i class="material-icons">person_add</i>Cadastre-se
                    </a>
                </li>

                <li class="nav-item ">
                    <a class="nav-link" href="@Url.Action("Login", "Account")">
                        <i class="material-icons">fingerprint</i> Login
                    </a>
                </li>
                <li class="nav-item  active ">
                    <a class="nav-link" href="@Url.Action("ForgotPassword", "Account")">
                        <i class="material-icons">lock_open</i> Esqueci Minha Senha
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

Responsavel.WebMVC/Views/Shared/_dashBoardQuantitativo.cshtml
@model Responsavel.WebMVC.Models.Shared.BarraDashboardViewModel

<div class="row">
    
    @foreach (var item in Model.Item)
    {
        <div class="col-md-3 col-xs-6">
            <div class="card">

                <div class="card-header card-separado" onclick="CarregarEscolasProtocoladas()" data-background-color="@item.CssCorBarra">
                    <div class="row">
                        <div class="col-md-2">
                            <i class="material-icons">@item.Icone</i>
                        </div>
                        <div class="col-md-10" style="text-align: right">
                            <p class="category">@item.Descricao</p>
                            <h3 class="card-title">@($"{item.Valor:##,###}")</h3>
                        </div>
                    </div>
                </div>
                <div class="card-content">
                </div>
                <div class="card-footer">
                    <div class="stats">
                        <i class="material-icons">@item.Icone</i>
                        @item.Mensagem
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Responsavel.WebMVC/Views/Shared/_dicasDeUsoGrafico.cshtml
<hr />
<p class="category dicas dicas-de-uso"><span class="text-warning">*</span>Dicas de uso:</p>
<p class="category dicas dicas-de-uso">Passe o cursor em cima do gráfico e veja a porcentagem de erros e acertos</p>
<p class="category dicas dicas-de-uso">Clique na legenda de um item para ocultar o resultado, clique novamente para reexibir</p>

Responsavel.WebMVC/Views/Shared/_dicasDeUsoTabela.cshtml
<hr />
            
<div>
    <p class="category dicas dicas-de-uso"><span class="text-warning">*</span>Dicas de uso:</p>
    <p class="category dicas dicas-de-uso">Para organizar por ordem alfabética ou numérica clique nos títulos das colunas.</p>
    <p class="category dicas dicas-de-uso">Utilize o campo "Pesquisar na tabela" para filtrar informações e facilitar sua leitura dos dados.</p>
</div>

Responsavel.WebMVC/Views/Shared/_footer.cshtml
@using Responsavel.WebMVC.App_Helpers
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
                <li>
                    @Html.ActionLink($"{ViewBag.Title}", "Index", "Home")
                </li>
            </ul>
        </nav>
        <p class="copyright pull-right">
            Versão : @Html.AssemblyVersion()
        </p>
        <p class="copyright pull-right">
            &copy; 2016-
            <script>
                document.write(new Date().getFullYear())
            </script>
            <a href="http://lintelligence.com.br">L'Intelligence</a> /* life runs on code! */
        </p>
    </div>
</footer>