Responsavel.WebMVC/Models/RelatorioQuantitativoDisciplina/RelatorioQuantitativoDisciplinaModelList.cs
// 18:28 04 10 2017  Atena.WebMVC  Atena.Web.Solution

using System;
using System.Collections.Generic;
using AMais.Responsavel.DTO.Integracao;
using AMais.Responsavel.DTO.Integracao.AgendaDoEstudante;
using Responsavel.WebMVC.Models.Shared;

namespace Responsavel.WebMVC.Models.RelatorioQuantitativoDisciplina
{
    [Serializable]
    public class RelatorioQuantitativoDisciplinaModelList
    {
        public ModelPaginacaoEOrdenacao PaginacaoEOrdenacao { get; set; }

        public AvaliacaoRelatorioPesquisaDTO Pesquisa { get; set; }

        public IEnumerable<AvaliacaoQuantitativaDisciplinaDTO> Registros { get; set; }

        public BarraDashboardViewModel BarraDashboard { get; set; }

        public IEnumerable<EstudanteDadosDTO> Estudantes { get; set; }
    }
}

Responsavel.WebMVC/Controllers/RelatorioQuantitativoDisciplinaController.cs
// 10:43 18 03 2018  AvaliacaoDiagnostica.WebMVC  AvaliacaoDiagnostica.Solution

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using AMais.Responsavel.Application.Interface.Integracao;
using AMais.Responsavel.Application.Interface.Integracao.AgendaDoEstudante;
using AMais.Responsavel.DTO.Integracao;
using AMais.Responsavel.DTO.Integracao.AgendaDoEstudante;
using Responsavel.WebMVC.Models.RelatorioQuantitativoDisciplina;
using Responsavel.WebMVC.Models.Shared;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class RelatorioQuantitativoDisciplinaController : BaseController
    {
        private readonly IRelatorioAvaliacaoQuantitativoAppService _relatorioQuantitativoAppService;
        private readonly IObterDadosUsuario _obterDadosUsuario;
        private readonly IAmaisTurmaEstudanteAppService _amaisTurmaEstudanteAppService;
        private readonly ITokenAppService _tokenAppService;

        public RelatorioQuantitativoDisciplinaController(IRelatorioAvaliacaoQuantitativoAppService relatorioQuantitativoAppService, ITokenAppService tokenAppService, IObterDadosUsuario obterDadosUsuario, IAmaisTurmaEstudanteAppService amaisTurmaEstudanteAppService)
        {
            _relatorioQuantitativoAppService = relatorioQuantitativoAppService;
            _tokenAppService = tokenAppService;
            _obterDadosUsuario = obterDadosUsuario;
            _amaisTurmaEstudanteAppService = amaisTurmaEstudanteAppService;
        }

        private IEnumerable<EstudanteDadosDTO> ObterDados()
        {
            var listaDados = new List<EstudanteDadosDTO>();

            var estudantes = _obterDadosUsuario.ObterDados();

            foreach (var estudante in estudantes)
            {
                var dados = _amaisTurmaEstudanteAppService.ObterTurmaEstudante(estudante.Token);

                estudante.Nome = dados.NomeEstudante;
                estudante.DescricaoAno = dados.DescricaoAno;
                estudante.DescricaoTurma = dados.DescricaoTurma;
                estudante.AnoLetivo = dados.AnoLetivo;


                listaDados.Add(estudante);
            }

            return listaDados;
        }


        private RelatorioQuantitativoDisciplinaModelList CarregarViewDataAsync(RelatorioQuantitativoDisciplinaModelList model = null)
        {
            if (model == null)
                model = new RelatorioQuantitativoDisciplinaModelList();

            if (model.PaginacaoEOrdenacao == null)
                model.PaginacaoEOrdenacao = new ModelPaginacaoEOrdenacao() { SortOrder = "Matricula", SortDirection = "ASC", SortOld = "Matricula" };

            model.Estudantes = ObterDados().OrderBy(x => x.DescricaoAno);

            return model;
        }

        private async Task<RelatorioQuantitativoDisciplinaModelList> CarregarViewDataPesquisaAsync(RelatorioQuantitativoDisciplinaModelList model)
        {
            var task = Task.Run(() => _relatorioQuantitativoAppService.ObterPorDisciplina(model.Pesquisa));
            model.Registros = await task;

            var relatorioAvaliacaoEfetividadeDtos = model.Registros.ToList();

            DefineBarraDashboard(model, relatorioAvaliacaoEfetividadeDtos);

            return model;
        }

        private static void DefineBarraDashboard(RelatorioQuantitativoDisciplinaModelList model, IReadOnlyCollection<AvaliacaoQuantitativaDisciplinaDTO> relatorioAvaliacaoEfetividadeDtos)
        {
            var totalAcertos = relatorioAvaliacaoEfetividadeDtos.Sum(x => x.TotalAcerto);
            var totalErros = relatorioAvaliacaoEfetividadeDtos.Sum(x => x.TotalErro);
            var efetividade = (totalAcertos + totalErros) > 0 ? Math.Round(totalAcertos / (totalAcertos + totalErros) * 100, 2) : 0;

            var icone = "";
            var cssCorBarra = "";
            if (efetividade >= 66)
            {
                icone = "trending_up";
                cssCorBarra = "efetividade_up";
            }
            else if (efetividade >= 33 && efetividade < 66)
            {
                icone = "trending_flat";
                cssCorBarra = "efetividade_media";
            }
            else if (efetividade < 33)
            {
                icone = "trending_down";
                cssCorBarra = "efetividade_down";
            }

            model.BarraDashboard = new BarraDashboardViewModel { Item = new List<ItemBarraDashboardViewModel>() };
            model.BarraDashboard.Item.Add(new ItemBarraDashboardViewModel
            {
                Icone = "group",
                CssCorBarra = "tarefa",
                Descricao = "Total de Avaliações",
                Mensagem = "Quantidade de avaliações que este relatório contempla",
                Valor = relatorioAvaliacaoEfetividadeDtos.Select(x => x.DescricaoAvaliacao).Distinct().Count()
            });
            model.BarraDashboard.Item.Add(new ItemBarraDashboardViewModel()
            {
                Icone = "perm_identity",
                CssCorBarra = "aula",
                Descricao = "Total de Questões",
                Mensagem = " Quantidade de questões que este relatório contempla",
                Valor = relatorioAvaliacaoEfetividadeDtos.Sum(x => x.TotalQuestao)
            });
            model.BarraDashboard.Item.Add(new ItemBarraDashboardViewModel()
            {
                Icone = "assignment",
                CssCorBarra = "trabalho",
                Descricao = "Total de Disciplinas",
                Mensagem = "Quantidade de disciplinas que este relatório contempla",
                Valor = relatorioAvaliacaoEfetividadeDtos.Sum(x => x.TotalDisciplina)
            });
            model.BarraDashboard.Item.Add(new ItemBarraDashboardViewModel()
            {
                Icone = icone,
                CssCorBarra = cssCorBarra,
                Descricao = "Efetividade",
                Mensagem = $"Porcentual de acertos. Acertos x Erros {totalAcertos:n0} x {totalErros:n0} ",
                Valor = efetividade
            });
        }

        public ActionResult Index()
        {
            GetModelStateData();

            var model = new RelatorioQuantitativoDisciplinaModelList
            {
                PaginacaoEOrdenacao = (ModelPaginacaoEOrdenacao)TempData["PaginacaoEOrdenacao"],
                Pesquisa = (AvaliacaoRelatorioPesquisaDTO)TempData["Pesquisa"]
            };

            if (!_tokenAppService.ObterTodos().Any())
            {
                ModelState.AddModelError("Erro", "Informe primeiramente seu token de acesso!");
                return RedirectToAction("InformarToken", "Token");
            }

            TempData["PaginacaoEOrdenacao"] = null;
            TempData["Pesquisa"] = null;
            model = CarregarViewDataAsync(model);

            return View(model);
        }
        
        public async Task<PartialViewResult> ExibirRelatorio(AvaliacaoRelatorioPesquisaDTO pesquisa, int turmaEstudanteId)
        {
            var model = new RelatorioQuantitativoDisciplinaModelList { Pesquisa = pesquisa };

            var listaTurmaEstudante = new int[] { turmaEstudanteId };

            model.Pesquisa.TurmaEstudanteId = listaTurmaEstudante;

            model = await CarregarViewDataPesquisaAsync(model);

            return await Task.Run(() => PartialView("_exibirRelatorio", model));
        }

        public async Task<ActionResult> LimparPesquisa(RelatorioQuantitativoDisciplinaModelList model)
        {
            TempData["PaginacaoEOrdenacao"] = model.PaginacaoEOrdenacao;
            return await Task.Run<ActionResult>(() => RedirectToAction("Index"));
        }

    }
}

Responsavel.WebMVC/Views/RelatorioQuantitativoDisciplina/Index.cshtml
@model Responsavel.WebMVC.Models.RelatorioQuantitativoDisciplina.RelatorioQuantitativoDisciplinaModelList

@{
    ViewBag.Title = "Relatório Quantitativo por Disciplina";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    Html.RenderPartial("_scriptsDaPagina");
}


<section class="content">

    <div class="container-fluid">
        
        <div class="row">
            
            <div div class="col-lg-10 col-md-10 col-sm-10 ml-auto mr-auto">

                @{
                    Html.RenderPartial("_estudantes", Model);
                }

            </div>

        </div>

        <div class="row">

            <div div class="col-lg-10 col-md-10 col-sm-10 ml-auto mr-auto">
                
                <div id="divRelatorio"></div>

            </div>

        </div>

    </div>

</section>


@section scripts {

    @Scripts.Render("~/bundles/Chart")
    
    <script>

        $(document).ready(function () {

            ObterRelatorio = function(turmaEstudanteId) {


                $.ajax({
                    url: "/RelatorioQuantitativoDisciplina/ExibirRelatorio?turmaEstudanteId=" + turmaEstudanteId,
                    type: 'GET',
                    dataType: 'HTML',
                    success: function (result) {

                        setTimeout(function () {

                            $('#divRelatorio').html(result);

                        }, 0);
                    }
                });

            };


        });

    </script>

}

Responsavel.WebMVC/Views/RelatorioQuantitativoDisciplina/_estudantes.cshtml
@model Responsavel.WebMVC.Models.RelatorioQuantitativoDisciplina.RelatorioQuantitativoDisciplinaModelList

@{
    var listaAnoLetivo = Model.Estudantes.Select(x => x.AnoLetivo).Distinct();
}


@foreach(var anoletivo in listaAnoLetivo)
{
    <div class="row">
            
        <div class="col-md-10 col-md-offset-1">
                
            <h4 class="title" style="cursor: pointer; margin-left: 15px;" data-toggle="collapse" href="#collapse_@anoletivo" role="button" aria-expanded="false" aria-controls="collapse_@anoletivo">
                @anoletivo
            </h4>
            
            <hr />

            <div id="collapse_@anoletivo" class="collapse">

                <div class="row">

                    @foreach (var estudante in Model.Estudantes.Where(x => x.AnoLetivo == anoletivo))
                    {
                        <div class="col-md-4">

                            <div class="card card-estudante">

                                <div class="card-header">

                                    <a class="imagem" style="background: url('@estudante.CaminhoImagem') no-repeat; background-size: cover; background-position: center; "></a>

                                </div>

                                <div class="card-content">

                                    @estudante.DescricaoAno

                                    <br />

                                    @estudante.Nome



                                </div>

                                <div class="card-footer">

                                    <button type="button" class="btn btn-primary btn-block" onclick="ObterRelatorio(@estudante.TurmaEstudanteId)">
                                        Exibir Relatório
                                    </button>


                                </div>


                            </div>

                        </div>
                    }

                </div>

            </div>



        </div>
            

    </div>

}

Responsavel.WebMVC/Views/RelatorioQuantitativoDisciplina/_exibirRelatorio.cshtml
@model Responsavel.WebMVC.Models.RelatorioQuantitativoDisciplina.RelatorioQuantitativoDisciplinaModelList
@{

    Html.RenderPartial("../Shared/_dashBoardQuantitativo", Model.BarraDashboard);
    Html.RenderPartial("_graficoDisciplina", Model);
    Html.RenderPartial("_lista", Model);

}


<script type="text/javascript">

    $(document).ready(function () {

        waitingDialog.hide();
    });

</script>

Responsavel.WebMVC/Views/RelatorioQuantitativoDisciplina/_graficoDisciplina.cshtml
@using Newtonsoft.Json
@model Responsavel.WebMVC.Models.RelatorioQuantitativoDisciplina.RelatorioQuantitativoDisciplinaModelList

@{
    ViewBag.Acertos = JsonConvert.SerializeObject(Model.Registros.Select(x => new { Valor = x.PercentualAcerto, Nome = x.Legenda }));
    ViewBag.Erros = JsonConvert.SerializeObject(Model.Registros.Select(x => new { Valor = x.PercentualErro, Nome = x.Legenda }));
    ViewBag.TotalAcertos = JsonConvert.SerializeObject(Model.Registros.Select(x => new { Valor = x.TotalAcerto, Nome = x.Legenda }));
    ViewBag.TotalErros = JsonConvert.SerializeObject(Model.Registros.Select(x => new { Valor = x.TotalErro, Nome = x.Legenda }));
    ViewBag.Legenda = JsonConvert.SerializeObject(Model.Registros.Select(x => x.Legenda));
    ViewBag.TotalQuestoes = Model.BarraDashboard.Item[2].Valor;
}

<div class="card">
    <div class="relatorio-m" data-background-color="grafico">
        <div class="ct-chart">
            <canvas id="graficoAbsoluto"></canvas>
        </div>
    </div>
</div>

<div class="card">
    <div class="relatorio-m" data-background-color="grafico">
        <div class="ct-chart">
            <canvas id="graficoPercentual"></canvas>
        </div>
    </div>
    <div class="card-content">
        <h4 class="card-title">Total de questões avaliadas nestas turmas</h4>
        <h3 class="card-title">@Model.Registros.Sum(x => x.TotalAcerto + x.TotalErro)</h3>
        <p class="category">Total de questões das avaliações respondidas pelos estudantes das turmas.</p>
        <p class="category">Número de estudantes total das turmas X o número de questões das avaliações.</p>
        <p class="category">Questões não respondidas e/ou anuladas não são contadas.</p>
        @{Html.RenderPartial("../Shared/_dicasDeUsoGrafico");}
    </div>
</div>


<script language="javascript">

    $(document).ready(function() {

        window.chartColors = {
            red: 'rgba(153, 0, 0, 0.6)',
            blue: 'rgba(0, 0, 153, 0.6)',
        };

        var labels = [], acertos = [], erros = [], totalAcertos = [], totalErros = [];

        $.map(JSON.parse('@Html.Raw(ViewBag.Legenda)'), function(item) {
            labels.push(item);
        });

        $.map(JSON.parse('@Html.Raw(ViewBag.Acertos)'), function(item) {
            acertos.push(item.Valor);
        });

        $.map(JSON.parse('@Html.Raw(ViewBag.Erros)'), function(item) {
            erros.push(item.Valor);
        });

        $.map(JSON.parse('@Html.Raw(ViewBag.TotalAcertos)'), function(item) {
            totalAcertos.push(item.Valor);
        });

        $.map(JSON.parse('@Html.Raw(ViewBag.TotalErros)'), function(item) {
            totalErros.push(item.Valor);
        });

        var ctx = document.getElementById("graficoAbsoluto");
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: labels,
                datasets: [
                    {
                        label: 'Acertos',
                        data: totalAcertos,
                        borderColor: window.chartColors.blue,
                        backgroundColor: window.chartColors.blue,
                        fill: true,
                        cubicInterpolationMode: 'monotone'
                    }, {
                        label: 'Erros',
                        data: totalErros,
                        borderColor: window.chartColors.red,
                        backgroundColor: window.chartColors.red,
                        fill: true,
                    }

                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                title: {
                    display: true,
                    text: 'Quantitativo por Disciplina - Números absolutos'
                },
                tooltips: {
                    mode: 'index'
                },
                scales: {
                    xAxes: [
                        {
                            display: true,
                            scaleLabel: {
                                display: true
                            },
                            ticks: {
                                display: true,
                                stepSize: 0,
                                min: 0,
                                autoSkip: false,
                                fontSize: 9,
                                padding: 12
                            }
                        }
                    ],
                    yAxes: [
                        {
                            display: true,
                            scaleLabel: {
                                display: true,
                                labelString: 'Números absolutos'
                            },
                            ticks: {
                                suggestedMin: 0,
                                suggestedMax: @ViewBag.TotalQuestoes,
                            }
                        }
                    ]
                }
            }

        });

        var ctxPercentual = document.getElementById("graficoPercentual");
        var myChartPercentual = new Chart(ctxPercentual, {
            type: 'bar',
            data: {
                labels: labels,
                datasets: [
                    {
                        label: '% Acertos',
                        data: acertos,
                        borderColor: window.chartColors.blue,
                        backgroundColor: window.chartColors.blue,
                        fill: true,
                        cubicInterpolationMode: 'monotone'
                    }, {
                        label: '% Erros',
                        data: erros,
                        borderColor: window.chartColors.red,
                        backgroundColor: window.chartColors.red,
                        fill: true,
                    }

                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                title: {
                    display: true,
                    text: 'Quantitativo por Disciplina - Percentual por aproveitamento'
                },
                tooltips: {
                    mode: 'index'
                },
                scales: {
                    xAxes: [
                        {
                            stacked: true,
                            display: true,
                            scaleLabel: {
                                display: true
                            },
                            ticks: {
                                display: true,
                                stepSize: 0,
                                min: 0,
                                autoSkip: false,
                                fontSize: 9,
                                padding: 12
                            }
                        }
                    ],
                    yAxes: [
                        {
                            stacked: true,
                            display: true,
                            scaleLabel: {
                                display: true,
                                labelString: 'Percentual'
                            },
                            ticks: {
                                suggestedMin: 0,
                                suggestedMax: @ViewBag.TotalQuestoes,
                            }
                        }
                    ]
                }
            }

        });


    });

</script>

Responsavel.WebMVC/Views/RelatorioQuantitativoDisciplina/_lista.cshtml
@model Responsavel.WebMVC.Models.RelatorioQuantitativoDisciplina.RelatorioQuantitativoDisciplinaModelList

@using (Html.BeginForm("LimparPesquisa", "RelatorioQuantitativoDisciplina", FormMethod.Post, new { id = "Lista-Escola-Usuario" }))
{

    <div class="card">

        <div class="card-header card-header-icon" data-background-color="blue">
            <i class="material-icons">view_list</i>
        </div>

        <div class="card-content">
            <h3 class="card-title">Relatório Quantitativo por Disciplina</h3>

            @Html.AntiForgeryToken()

            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.Page)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortOrder)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortDirection)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortOld)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.UrlRetorno)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.PaginacaoEOrdenacaoUrlRetorno)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.PesquisaUrlRetorno)

            <div class="table-responsive">

                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width: 100%">
                    <thead>
                        <tr>
                            <th style="width: 20%">
                                Avaliação
                            </th>
                            <th style="width: 20%">
                                Área
                            </th>
                            <th style="width: 20%">
                                Disciplina
                            </th>
                            <th>
                                Turma
                            </th>
                            <th>
                                Questões
                            </th>
                            <th>
                                Acerto
                            </th>
                            <th>
                                Erro
                            </th>
                            <th>
                                % Acerto
                            </th>
                            <th>
                                % Erro
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Registros)
                {
                        <tr>
                            <td>@item.DescricaoAvaliacao</td>
                            <td>@item.DescricaoArea</td>
                            <td>@item.DescricaoDisciplina</td>
                            <td style="text-align: center">@item.TotalTurma</td>
                            <td style="text-align: center">@item.TotalAvaliacao</td>
                            <td style="text-align: center">@item.TotalAcerto</td>
                            <td style="text-align: center">@item.TotalErro</td>
                            <td style="text-align: center">@item.PercentualAcerto</td>
                            <td style="text-align: center">@item.PercentualErro</td>
                            <td class="td-actions" style="text-align: right"></td>
                        </tr>
        }
                    </tbody>
                </table>
            </div>

            @{Html.RenderPartial("../Shared/_dicasDeUsoTabela");}
        </div>

    </div>

}



@section scripts {

    @Scripts.Render("~/bundles/dataTable")

}

<script type="text/javascript">

    $(document).ready(function () {

        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [25, 50, 100, 150, 200, 250, -1],
                [25, 50, 100, 150, 200, 250, "Todos"]
            ],
            responsive: true,
            language: {
                "url": '/Content/jquery.datatables.language.jSon',
                search: "_INPUT_",
                searchPlaceholder: " contendo...",
            },
            buttons: [],
            "columnDefs": [
                {
                    "targets": [9],
                    "visible": true,
                    "searchable": false,
                    "orderable": false
                }
            ]
        });

        setTimeout(function () {
            $('.material-datatables').show();
            $('#aguardeCarregar').hide();
        }, 1000);


        var table = $('#datatables').DataTable();

        // Edit record
        table.on('click', '.edit', function () {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        $('.card .material-datatables label').addClass('form-group');

    });
</script>

Responsavel.WebMVC/Views/RelatorioQuantitativoDisciplina/_pesquisa.cshtml
@model Responsavel.WebMVC.Models.RelatorioQuantitativoDisciplina.RelatorioQuantitativoDisciplinaModelList


@using (Html.BeginForm("LimparPesquisa", "RelatorioQuantitativoDisciplina", FormMethod.Post, new { id = "Form-Pesquisar" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.Page)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortOrder)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortDirection)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortOld)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.UrlRetorno)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.PaginacaoEOrdenacaoUrlRetorno)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.PesquisaUrlRetorno)


    <div class="card">

        <div class="card-header-noborder" data-background-color="blue">
            <h4 class="title">Pesquisa</h4>
            <p class="category">Escolha a escola, turma e a avaliação que você deseja ver os resultados. Depois, clique em exibir dados.</p>
        </div>

        <div class="card-content">

            @{ Html.RenderPartial("_pesquisaRelatorio", Model.Pesquisa);}

            <div class="footer pull-left">
                <button class="btn btn-custom-default cancel">
                    Limpar pesquisa
                </button>

                <button class="btn btn-custom-salvar" id="btnExibirRelatorio">
                    Exibir dados
                </button>
            </div>

        </div>
    </div>
}



<script type="text/javascript">

    $(document).ready(function () {

        var form = document.getElementById("Form-Pesquisar"),
            jqForm = $(form);

        $("#btnExibirRelatorio").click(function (e) {

            waitingDialog.show();

            e.preventDefault();
            if (jqForm.valid()) {

                var model = jqForm.serializeArray();

                $.ajax({
                    url: "/RelatorioQuantitativoDisciplina/ExibirRelatorio",
                    type: 'GET',
                    data: model,
                    dataType: 'HTML',
                    success: function (result) {

                        setTimeout(function () {

                            $('#divRelatorio').html(result);

                        }, 0);
                    }
                });
            }
        });
    });

</script>

Responsavel.WebMVC/Views/RelatorioQuantitativoDisciplina/_scriptsDaPagina.cshtml
<script type="text/javascript">

    $(document).ready(function() {

        $("#RelatorioQuantitavivoDisciplina").addClass("active");
    });
    
    
</script>