Responsavel.WebMVC/Models/RelatorioQualitativoDescritor/RelatorioQualitativoDescritorModelList.cs
// 18:28 04 10 2017  Atena.WebMVC  Atena.Web.Solution

using System;
using System.Collections.Generic;
using AMais.Responsavel.DTO.Integracao;
using AMais.Responsavel.DTO.Integracao.AgendaDoEstudante;
using Responsavel.WebMVC.Models.Shared;

namespace Responsavel.WebMVC.Models.RelatorioQualitativoDescritor
{
    [Serializable]
    public class RelatorioQualitativoDescritorModelList
    {
        public ModelPaginacaoEOrdenacao PaginacaoEOrdenacao { get; set; }

        public AvaliacaoRelatorioPesquisaDTO Pesquisa { get; set; }

        public IEnumerable<AvaliacaoQualitativaDescritorDTO> Registros { get; set; }
        public IEnumerable<AvaliacaoQuantitativaDTO> RegistrosAvaliacao { get; set; }

        public BarraDashboardViewModel BarraDashboard { get; set; }

        public IEnumerable<EstudanteDadosDTO> Estudantes { get; set; }

    }
}

Responsavel.WebMVC/Controllers/RelatorioQualitativoDescritorController.cs
// 15:20 25 03 2018  AvaliacaoDiagnostica.WebMVC  AvaliacaoDiagnostica.Solution

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AMais.Responsavel.Application.Interface;
using AMais.Responsavel.Application.Interface.Integracao;
using AMais.Responsavel.Application.Interface.Integracao.AgendaDoEstudante;
using AMais.Responsavel.DTO.Integracao;
using AMais.Responsavel.DTO.Integracao.AgendaDoEstudante;
using Responsavel.WebMVC.Models.RelatorioQualitativoDescritor;
using Responsavel.WebMVC.Models.Shared;

namespace Responsavel.WebMVC.Controllers
{
    [Authorize]
    public class RelatorioQualitativoDescritorController : BaseController
    {
        private readonly IRelatorioAvaliacaoQualitativoAppService _relatorioQualitativoAppService;
        private readonly IRelatorioAvaliacaoQuantitativoAppService _relatorioQuantitativoAppService;
        private readonly IObterDadosUsuario _obterDadosUsuario;
        private readonly IAmaisTurmaEstudanteAppService _amaisTurmaEstudanteAppService;
        private readonly ITokenAppService _tokenAppService;

        public RelatorioQualitativoDescritorController(IRelatorioAvaliacaoQualitativoAppService relatorioQualitativoAppService, IRelatorioAvaliacaoQuantitativoAppService relatorioQuantitativoAppService, ITokenAppService tokenAppService, IObterDadosUsuario obterDadosUsuario, IAmaisTurmaEstudanteAppService amaisTurmaEstudanteAppService)
        {
            _relatorioQualitativoAppService = relatorioQualitativoAppService;
            _relatorioQuantitativoAppService = relatorioQuantitativoAppService;
            _tokenAppService = tokenAppService;
            _obterDadosUsuario = obterDadosUsuario;
            _amaisTurmaEstudanteAppService = amaisTurmaEstudanteAppService;
        }

        private IEnumerable<EstudanteDadosDTO> ObterDados()
        {
            var listaDados = new List<EstudanteDadosDTO>();

            var estudantes = _obterDadosUsuario.ObterDados();

            foreach (var estudante in estudantes)
            {
                var dados = _amaisTurmaEstudanteAppService.ObterTurmaEstudante(estudante.Token);

                estudante.Nome = dados.NomeEstudante;
                estudante.DescricaoAno = dados.DescricaoAno;
                estudante.DescricaoTurma = dados.DescricaoTurma;
                estudante.AnoLetivo = dados.AnoLetivo;


                listaDados.Add(estudante);
            }

            return listaDados;
        }

        private RelatorioQualitativoDescritorModelList CarregarViewDataAsync(RelatorioQualitativoDescritorModelList model = null)
        {
            if (model == null)
                model = new RelatorioQualitativoDescritorModelList();

            if (model.PaginacaoEOrdenacao == null)
                model.PaginacaoEOrdenacao = new ModelPaginacaoEOrdenacao() { SortOrder = "Matricula", SortDirection = "ASC", SortOld = "Matricula" };

            model.Estudantes = ObterDados().OrderBy(x => x.DescricaoAno);

            return model;
        }

        private async Task<RelatorioQualitativoDescritorModelList> CarregarViewDataPesquisaAsync(RelatorioQualitativoDescritorModelList model)
        {
            var taskRegistroAvaliacao = Task.Run(() => _relatorioQuantitativoAppService.ObterPorAvaliacao(model.Pesquisa));
            model.RegistrosAvaliacao = await taskRegistroAvaliacao;

            var task = Task.Run(() => _relatorioQualitativoAppService.ObterPorDescritor(model.Pesquisa));
            model.Registros = await task;

            var relatorioAvaliacaoEfetividadeDtos = model.RegistrosAvaliacao.ToList();
            DefineBarraDashboard(model, relatorioAvaliacaoEfetividadeDtos);
            
            return model;
        }

        private static void DefineBarraDashboard(RelatorioQualitativoDescritorModelList model, IReadOnlyCollection<AvaliacaoQuantitativaDTO> relatorioAvaliacaoEfetividadeDtos)
        {
            var totalAcertos = relatorioAvaliacaoEfetividadeDtos.Sum(x => x.TotalAcerto);
            var totalErros = relatorioAvaliacaoEfetividadeDtos.Sum(x => x.TotalErro);
            var efetividade = (totalAcertos + totalErros) > 0 ? Math.Round(totalAcertos / (totalAcertos + totalErros) * 100, 2) : 0;

            var icone = "";
            var cssCorBarra = "";
            if (efetividade >= 66)
            {
                icone = "trending_up";
                cssCorBarra = "efetividade_up";
            }
            else if (efetividade >= 33 && efetividade < 66)
            {
                icone = "trending_flat";
                cssCorBarra = "efetividade_media";
            }
            else if (efetividade < 33)
            {
                icone = "trending_down";
                cssCorBarra = "efetividade_down";
            }

            model.BarraDashboard = new BarraDashboardViewModel { Item = new List<ItemBarraDashboardViewModel>() };
            model.BarraDashboard.Item.Add(new ItemBarraDashboardViewModel
            {
                Icone = "group",
                CssCorBarra = "tarefa",
                Descricao = "Total de Avaliações",
                Mensagem = "Quantidade de avaliações que este relatório contempla",
                Valor = relatorioAvaliacaoEfetividadeDtos.Select(x => x.AvaliacaoId).Distinct().Count()
            });
            model.BarraDashboard.Item.Add(new ItemBarraDashboardViewModel()
            {
                Icone = "perm_identity",
                CssCorBarra = "aula",
                Descricao = "Total de Questões",
                Mensagem = " Quantidade de questões que este relatório contempla",
                Valor = relatorioAvaliacaoEfetividadeDtos.Sum(x => x.TotalQuestao)
            });
            model.BarraDashboard.Item.Add(new ItemBarraDashboardViewModel()
            {
                Icone = "assignment",
                CssCorBarra = "trabalho",
                Descricao = "Total de Disciplinas",
                Mensagem = "Quantidade de disciplinas que este relatório contempla",
                Valor = relatorioAvaliacaoEfetividadeDtos.Sum(x => x.TotalDisciplina)
            });
            model.BarraDashboard.Item.Add(new ItemBarraDashboardViewModel()
            {
                Icone = icone,
                CssCorBarra = cssCorBarra,
                Descricao = "Efetividade",
                Mensagem = $"Porcentual de acertos. Acertos x Erros {totalAcertos:n0} x {totalErros:n0} ",
                Valor = efetividade
            });
        }


        public ActionResult Index()
        {
            GetModelStateData();

            var model = new RelatorioQualitativoDescritorModelList
            {
                PaginacaoEOrdenacao = (ModelPaginacaoEOrdenacao)TempData["PaginacaoEOrdenacao"],
                Pesquisa = (AvaliacaoRelatorioPesquisaDTO)TempData["Pesquisa"]
            };

            if (!_tokenAppService.ObterTodos().Any())
            {
                ModelState.AddModelError("Erro", "Informe primeiramente seu token de acesso!");
                return RedirectToAction("InformarToken", "Token");
            }

            TempData["PaginacaoEOrdenacao"] = null;
            TempData["Pesquisa"] = null;
            model = CarregarViewDataAsync(model);

            return View(model);
        }

      
        public async Task<PartialViewResult> ExibirRelatorio(AvaliacaoRelatorioPesquisaDTO pesquisa, int turmaEstudanteId)
        {
            var model = new RelatorioQualitativoDescritorModelList { Pesquisa = pesquisa };

            var listaTurmaEstudante = new int[] { turmaEstudanteId };

            model.Pesquisa.TurmaEstudanteId = listaTurmaEstudante;

            model = await CarregarViewDataPesquisaAsync(model);

            return await Task.Run(() => PartialView("_exibirRelatorio", model));
        }

        public async Task<ActionResult> LimparPesquisa(RelatorioQualitativoDescritorModelList model)
        {
            TempData["PaginacaoEOrdenacao"] = model.PaginacaoEOrdenacao;
            return await Task.Run<ActionResult>(() => RedirectToAction("Index"));
        }

    }
}

Responsavel.WebMVC/Views/RelatorioQualitativoDescritor/Index.cshtml
@model Responsavel.WebMVC.Models.RelatorioQualitativoDescritor.RelatorioQualitativoDescritorModelList

@{
    ViewBag.Title = "Análise dos Descritores de Aprendizagem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    Html.RenderPartial("_scriptsDaPagina");
}


<section class="content">

    <div class="container-fluid">
        
        <div class="row">
            
            <div div class="col-lg-10 col-md-10 col-sm-10 ml-auto mr-auto">

                @{
                    Html.RenderPartial("_estudantes", Model);
                }

            </div>

        </div>

        <div class="row">

            <div div class="col-lg-10 col-md-10 col-sm-10 ml-auto mr-auto">

                <div id="divRelatorio"></div>

            </div>

        </div>


    </div>

</section>

@section scripts {

    @Scripts.Render("~/bundles/Chart")

    <script>

        $(document).ready(function () {

            ObterRelatorio = function(turmaEstudanteId) {


                $.ajax({
                    url: "/RelatorioQualitativoDescritor/ExibirRelatorio?turmaEstudanteId=" + turmaEstudanteId,
                    type: 'GET',
                    dataType: 'HTML',
                    success: function (result) {

                        setTimeout(function () {

                            $('#divRelatorio').html(result);

                        }, 0);
                    }
                });

            };


        });

    </script>

}

Responsavel.WebMVC/Views/RelatorioQualitativoDescritor/_estudantes.cshtml
@using Microsoft.ApplicationInsights.WindowsServer.Channel.Implementation
@model Responsavel.WebMVC.Models.RelatorioQualitativoDescritor.RelatorioQualitativoDescritorModelList

@{
    var listaAnoLetivo = Model.Estudantes.Select(x => x.AnoLetivo).Distinct();
}


@foreach(var anoletivo in listaAnoLetivo)
{
    <div class="row">
            
        <div class="col-md-10 col-md-offset-1">
                
            <h4 class="title" style="cursor: pointer; margin-left: 15px;" data-toggle="collapse" href="#collapse_@anoletivo" role="button" aria-expanded="false" aria-controls="collapse_@anoletivo">
                @anoletivo
            </h4>
            
            <hr />

            <div id="collapse_@anoletivo" class="collapse">
                
                <div class="row">
                    
                    @foreach(var estudante in Model.Estudantes.Where(x => x.AnoLetivo == anoletivo))
                    {
                        <div class="col-md-4">
                        
                            <div class="card card-estudante">
                                
                                <div class="card-header">
                                    
                                    <a class="imagem" style="background: url('@estudante.CaminhoImagem') no-repeat; background-size: cover; background-position: center; "></a>

                                </div>

                                <div class="card-content">

                                    @estudante.DescricaoAno

                                    <br />

                                    @estudante.Nome



                                </div>

                                <div class="card-footer">

                                    <button type="button" class="btn btn-primary btn-block" onclick="ObterRelatorio(@estudante.TurmaEstudanteId)">
                                        Exibir Relatório
                                    </button>


                                </div>


                            </div>

                        </div>
                    }

                </div>

            </div>



        </div>
            

    </div>

}

Responsavel.WebMVC/Views/RelatorioQualitativoDescritor/_exibirRelatorio.cshtml
@model Responsavel.WebMVC.Models.RelatorioQualitativoDescritor.RelatorioQualitativoDescritorModelList

@{

    Html.RenderPartial("../Shared/_dashBoardQuantitativo", Model.BarraDashboard);
    Html.RenderPartial("_graficoTurma");
    Html.RenderPartial("_listaDescritor", Model);
    Html.RenderPartial("_lista", Model);

}


<script type="text/javascript">

    $(document).ready(function () {

        waitingDialog.hide();
    });

</script>

Responsavel.WebMVC/Views/RelatorioQualitativoDescritor/_graficoTurma.cshtml
@model Responsavel.WebMVC.Models.RelatorioQualitativoDescritor.RelatorioQualitativoDescritorModelList

@using Newtonsoft.Json

@{
    ViewBag.Acertos = JsonConvert.SerializeObject(Model.Registros.GroupBy(x => new {x.AreaId, x.DescricaoArea}, (key, grupo) => new {key.AreaId, key.DescricaoArea, Valor = Math.Round(grupo.Average(x => x.PercentualAcerto), 2)}).ToList());
    ViewBag.Erros = JsonConvert.SerializeObject(Model.Registros.GroupBy(x => new {x.AreaId, x.DescricaoArea}, (key, grupo) => new {key.AreaId, key.DescricaoArea, Valor = Math.Round(grupo.Average(x => x.PercentualErro), 2)}).ToList());
    
    ViewBag.Legenda = JsonConvert.SerializeObject(Model.Registros.Select(x => new {x.AreaId, x.DescricaoArea}).Distinct());
}

<div class="card">
    <div class="relatorio-m" data-background-color="grafico">
        <div class="ct-chart">
            <canvas id="grafico"></canvas>
        </div>
    </div>
    <div class="card-content">
        <h4 class="card-title">Total de questões avaliadas.</h4>
        <h3 class="card-title">@Model.Registros.Sum(x => x.TotalAcerto + x.TotalErro)</h3>
        <p class="category">Total de questões da (s) avaliação (ões) respondida (s) pelos estudantes da (s) turma (s).</p>
        <p class="category">Questões não respondidas e/ou anuladas não são contadas.</p>
        @{Html.RenderPartial("../Shared/_dicasDeUsoGrafico");}
    </div>
</div>

<script language="javascript">

    $(document).ready(function() {

        window.chartColors = {
            red: 'rgba(153, 0, 0, 0.6)',
            blue: 'rgba(0, 0, 153, 0.6)',
            orange: 'rgb(255, 159, 64)',
            yellow: 'rgb(255, 205, 86)',
            green: 'rgb(75, 192, 192)',
            purple: 'rgb(153, 102, 255)',
            grey: 'rgb(201, 203, 207)'
        };

        var labels = [], acertos = [], erros = [];

        $.map(JSON.parse('@Html.Raw(ViewBag.Legenda)'), function(item) {
            labels.push(item.DescricaoArea);
        });

        $.map(JSON.parse('@Html.Raw(ViewBag.Acertos)'), function(item) {
            acertos.push(item.Valor);
        });

        $.map(JSON.parse('@Html.Raw(ViewBag.Erros)'), function(item) {
            erros.push(item.Valor);
        });

        var ctx = document.getElementById("grafico");
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: labels,
                datasets: [
                    {
                        label: '% Acertos',
                        data: acertos,
                        borderColor: window.chartColors.blue,
                        backgroundColor: window.chartColors.blue,
                        fill: true,
                        cubicInterpolationMode: 'monotone'
                    }, {
                        label: '% Erros',
                        data: erros,
                        borderColor: window.chartColors.red,
                        backgroundColor: window.chartColors.red,
                        fill: true,
                    }
                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                title: {
                    display: true,
                    text: 'Gráfico Qualitativo por Área'
                },
                tooltips: {
                    mode: 'index'
                },
                scales: {
                    xAxes: [
                        {
                            display: true,
                            scaleLabel: {
                                display: true
                            },
                            ticks: {
                                display: true,
                                stepSize: 0,
                                min: 0,
                                autoSkip: false,
                                fontSize: 9,
                                padding: 12
                            }
                        }
                    ],
                    yAxes: [
                        {
                            display: true,
                            scaleLabel: {
                                display: true,
                                labelString: 'Percentual'
                            },
                            ticks: {
                                suggestedMin: 0,
                                suggestedMax: 100,
                            }
                        }
                    ]
                }
            }
        });

        //window.onload = function() {
        //    var ctx = document.getElementById('canvas').getContext('2d');
        //    window.myLine = new Chart(ctx, config);
        //};

    });

</script>

Responsavel.WebMVC/Views/RelatorioQualitativoDescritor/_lista.cshtml
@model Responsavel.WebMVC.Models.RelatorioQualitativoDescritor.RelatorioQualitativoDescritorModelList

@using (Html.BeginForm("LimparPesquisa", "RelatorioQualitativoDescritor", FormMethod.Post, new { id = "Lista-Escola-Usuario" }))
{

    <div class="card">
        <div class="card-header card-header-icon" data-background-color="blue">
            <i class="material-icons">trending_up</i>
        </div>

        <div class="card-content">
            <h3 class="card-title">Análise dos Descritores de Aprendizagem</h3>

            @Html.AntiForgeryToken()

            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.Page)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortOrder)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortDirection)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortOld)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.UrlRetorno)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.PaginacaoEOrdenacaoUrlRetorno)
            @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.PesquisaUrlRetorno)

            <div class="table-responsive">
                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width: 100%">
                    <thead>
                        <tr>
                            <th>
                                ID
                            </th>
                            <th style="width: 40%">
                                Descritor
                            </th>
                            <th>
                                Área
                            </th>
                            <th>
                                Disciplinas
                            </th>
                            <th>
                                Total de Questões
                            </th>
                            <th>
                                Acertos
                            </th>
                            <th>
                                Erros
                            </th>
                            <th>
                                % Acertos
                            </th>
                            <th>
                                % Erros
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model.Registros)
                    {
                        <tr>
                            <td>@item.DescritorId</td>
                            <td>@item.DescricaoDescritor</td>
                            <td>@item.DescricaoArea</td>
                            <td style="text-align: center">@item.TotalDisciplina</td>
                            <td style="text-align: center">@item.TotalQuestao</td>
                            <td style="text-align: center">@item.TotalAcerto</td>
                            <td style="text-align: center">@item.TotalErro</td>
                            <td style="text-align: center">@item.PercentualAcerto</td>
                            <td style="text-align: center">@item.PercentualErro</td>
                            <td class="td-actions" style="text-align: right"></td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>

            @{Html.RenderPartial("../Shared/_dicasDeUsoTabela");}
        </div>

    </div>

}



@section scripts {

    @Scripts.Render("~/bundles/dataTable")

}

<script type="text/javascript">

    $(document).ready(function () {

        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [25, 50, 100, 150, 200, 250, -1],
                [25, 50, 100, 150, 200, 250, "Todos"]
            ],
            responsive: true,
            language: {
                "url": '/Content/jquery.datatables.language.jSon',
                search: "_INPUT_",
                searchPlaceholder: " contendo...",
            },
            dom: '<"row"<"col-md-6"l><"col-md-6"f>>rt<br/><"pull-left"<"pagination"<"row"<"col-md-2"i><"col-md-10"p>>>><"pull-righ"B><"clear">',
            buttons: [],
            "columnDefs": [
                {
                    "targets": [9],
                    "visible": true,
                    "searchable": false,
                    "orderable": false
                }
            ]
        });

        $('#datatables').addClass('newclass').removeClass('dataTable');
        setTimeout(function () {
            $('.material-datatables').show();
            $('#aguardeCarregar').hide();
        }, 1000);


        var table = $('#datatables').DataTable();

        // Edit record
        table.on('click', '.edit', function () {
            $tr = $(this).closest('tr');

            var data = table.row($tr).data();
            alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
        });

        $('.card .material-datatables label').addClass('form-group');

    });
</script>

Responsavel.WebMVC/Views/RelatorioQualitativoDescritor/_listaDescritor.cshtml
@using System.Globalization
@model Responsavel.WebMVC.Models.RelatorioQualitativoDescritor.RelatorioQualitativoDescritorModelList

@{
    var passo = 3;
    var faixaMinima = ((100 / 3) * (passo - 1));
    var faixaMaxima = 100;
    var corBarra = "";

    <div class="card">
        <div class="card-header card-header-icon" data-background-color="">
            <i class="material-icons">priority_high</i>
        </div>
        <div class="card-content">
            <h4 class="card-title-icon">Conforme porcentagem de acertos, os descritores são classificados em:</h4>
        </div>

        <ul>
            <li class="category">Descritores satisfatórios: acima de 65% de acertos.</li>
            <li class="category">Descritores parcialmente desenvolvidos: entre 33% e 65% de acertos.</li>
            <li class="category">Descritores em desenvolvimento Inicial: abaixo de 33% de acertos.</li>
        </ul>
    </div>

    while (faixaMinima >= 0)
    {
        <div class="card">

            @if (faixaMinima >= 66)
            {
                corBarra = "progress-bar progress-bar-success";
                <div class="card-header card-header-icon" data-background-color="green">
                    <i class="material-icons">trending_up</i>
                </div>
                <div class="card-content" data-toggle="collapse" data-parent="#accordion" href="#Faixa_@faixaMinima">
                    <h3 class="card-title-icon">Descritores Satisfatórios <i class="material-icons">swap_vert</i></h3>

                </div>

            }
            @if (faixaMinima >= 33 && faixaMinima < 66)
            {
                corBarra = "progress-bar progress-bar-warning";
                <div class="card-header card-header-icon" data-background-color="orange">
                    <i class="material-icons">trending_flat</i>
                </div>
                <div class="card-content" data-toggle="collapse" data-parent="#accordion" href="#Faixa_@faixaMinima">
                    <h3 class="card-title-icon">Descritores Parcialmente Desenvolvidos <i class="material-icons">swap_vert</i></h3>

                </div>

            }
            @if (faixaMinima < 33)
            {
                corBarra = "progress-bar progress-bar-danger";
                <div class="card-header card-header-icon" data-background-color="red">
                    <i class="material-icons">trending_down</i>
                </div>
                <div class="card-content" data-toggle="collapse" data-parent="#accordion" href="#Faixa_@faixaMinima">
                    <h3 class="card-title-icon">Descritores em Desenvolvimento Inicial <i class="material-icons">swap_vert</i></h3>

                </div>

            }
            <div class="panel-collapse collapse categoria-corpo show" id="Faixa_@faixaMinima" role="tabpanel" aria-labelledby="pesquisa-header">
                @{

                    var registrosComFiltro = Model.Registros.Where(x => x.PercentualAcerto >= faixaMinima && x.PercentualAcerto <= faixaMaxima).ToList();
                    foreach (var area in registrosComFiltro.Select(x => new { x.AreaId, x.DescricaoArea }).Distinct())
                    {
                        <div class="col-md-12">
                            <div class="panel panel-info linhaRelatorio">
                                <div class="panel-heading linhaRelatorioHeading">
                                    <h4>@area.DescricaoArea</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="col-md-12">
                                        @foreach (var registro in registrosComFiltro.Where(x => x.AreaId == area.AreaId))
                                        {
                                        <div>
                                            <p>@registro.DescricaoAvaliacao</p>
                                            <p>@registro.DescricaoDescritor</p>
                                        </div>
                                            <div class="progress">
                                                <div class="@corBarra" role="progressbar" aria-valuenow="@registro.PercentualAcerto.ToString(CultureInfo.InvariantCulture)"
                                                     aria-valuemin="0" aria-valuemax="100" style="width: @registro.PercentualAcerto.ToString(CultureInfo.InvariantCulture)%">
                                                    @registro.PercentualAcerto
                                                </div>
                                            </div>
                                        }

                                    </div>
                                </div>
                                @*<div class="panel-footer" style="text-align: right">
                                        <h4>Média atingida para @area.DescricaoArea : @Math.Round(registrosComFiltro.Where(x => x.AreaId == area.AreaId).Average(x => x.PercentualAcerto), 2)</h4>
                                    </div>*@
                            </div>

                        </div>
                    }
                }
            </div>

        </div>

                        faixaMinima = ((100 / 3) * (--passo - 1));
                        faixaMaxima = ((100 / 3) * passo);
                    }

}

Responsavel.WebMVC/Views/RelatorioQualitativoDescritor/_pesquisa.cshtml
@model Responsavel.WebMVC.Models.RelatorioQualitativoDescritor.RelatorioQualitativoDescritorModelList

@using (Html.BeginForm("LimparPesquisa", "RelatorioQualitativoDescritor", FormMethod.Post, new { id = "Form-Pesquisar" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.Page)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortOrder)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortDirection)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.SortOld)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.UrlRetorno)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.PaginacaoEOrdenacaoUrlRetorno)
    @Html.HiddenFor(m => Model.PaginacaoEOrdenacao.PesquisaUrlRetorno)


    <div class="card">

        <div class="card-header-noborder" data-background-color="blue">
            <h4 class="title">Pesquisa</h4>
            <p class="category">Escolha a escola, turma e a avaliação que você deseja ver os resultados. Depois, clique em exibir dados.</p>
        </div>

        <div class="card-content">

            @{ Html.RenderPartial("_pesquisaRelatorio", Model.Pesquisa);}

            <div class="footer pull-left">
                <button class="btn btn-custom-default cancel">
                    Limpar pesquisa
                </button>

                <button class="btn btn-custom-salvar" id="btnExibirRelatorio">
                    Exibir dados
                </button>
            </div>

        </div>
    </div>
}



<script type="text/javascript">

    $(document).ready(function () {

        var form = document.getElementById("Form-Pesquisar"),
            jqForm = $(form);

        $("#btnExibirRelatorio").click(function (e) {

            waitingDialog.show();

            e.preventDefault();
            if (jqForm.valid()) {

                var model = jqForm.serializeArray();

                $.ajax({
                    url: "/RelatorioQualitativoDescritor/ExibirRelatorio",
                    type: 'GET',
                    data: model,
                    dataType: 'HTML',
                    success: function (result) {

                        setTimeout(function () {

                            $('#divRelatorio').html(result);

                        }, 0);
                    }
                });
            }
        });
    });

</script>

Responsavel.WebMVC/Views/RelatorioQualitativoDescritor/_scriptsDaPagina.cshtml
<script type="text/javascript">

    $(document).ready(function() {

        $("#RelatorioQualitativoDescritor").addClass("active");
    });
    

</script>